### ISSUE TITLE
Left to Right Versa Versa

### ISSUE THREAD

**Issue by NolvusMadeIt** [obrm/dev-home#1]
Hello, Im wondering which file do I change the language and the text from right to left?

**Comment by obrm** [comment]
Line 2 here
https://github.com/obrm/dev-home/blob/master/client/public/index.html

**Comment by NolvusMadeIt** [comment]
> Line 2 here
> https://github.com/obrm/dev-home/blob/master/client/public/index.html

Thank you so much, Id love to use this for my team and give you some feedback on it if its ok, not that thats probably what your looking for but, if I had any questions or suggestions, I'd most defiantly get back to you guys. Thank you again!
